# Generated by Django 5.0.6 on 2026-05-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnthemVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('verse_type', models.CharField(choices=[('verse', 'Куплет'), ('chorus', 'Припев')], max_length=10)),
                ('text_ky', models.TextField(verbose_name='Текст (кыргызский)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Текст (русский)')),
            ],
            options={
                'verbose_name': 'Строфа гимна',
                'verbose_name_plural': 'Строфы гимна',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_type', models.CharField(choices=[('flag', 'Флаг'), ('emblem', 'Герб'), ('anthem', 'Гимн')], max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('history', models.TextField(blank=True, verbose_name='История создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='symbols/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='symbols/audio/')),
            ],
            options={
                'verbose_name': 'Государственный символ',
                'verbose_name_plural': 'Государственные символы',
            },
        ),
        migrations.CreateModel(
            name='SymbolElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Элемент')),
                ('description', models.TextField(verbose_name='Описание')),
                ('meaning', models.TextField(blank=True, verbose_name='Значение')),
                ('x_percent', models.FloatField(default=50, help_text='X позиция в % от ширины')),
                ('y_percent', models.FloatField(default=50, help_text='Y позиция в % от высоты')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='symbols.symbol')),
            ],
            options={
                'verbose_name': 'Элемент символа',
                'verbose_name_plural': 'Элементы символа',
            },
        ),
    ]
