# Generated by Django 5.0.6 on 2026-05-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True)),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personalities/')),
                ('short_bio', models.CharField(max_length=300, verbose_name='Краткая биография')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('role', models.CharField(max_length=200, verbose_name='Историческая роль')),
                ('is_featured', models.BooleanField(default=False)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalities', to='history.historicalperiod', verbose_name='Эпоха')),
            ],
            options={
                'verbose_name': 'Историческая личность',
                'verbose_name_plural': 'Исторические личности',
                'ordering': ['birth_year'],
            },
        ),
    ]
