# Generated by Django 5.0.6 on 2026-05-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('period_type', models.CharField(choices=[('ancient', 'Древний Кыргызстан'), ('khaganate', 'Кыргызский каганат'), ('manas', 'Эпоха Манаса'), ('khanate', 'Кокандское ханство'), ('empire', 'Российская империя'), ('ussr', 'Советский период'), ('independent', 'Независимый Кыргызстан')], max_length=20, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/periods/')),
                ('start_year', models.IntegerField(verbose_name='Начало (год)')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='Конец (год)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#E8112D', help_text='HEX цвет для карточки', max_length=7)),
            ],
            options={
                'verbose_name': 'Исторический период',
                'verbose_name_plural': 'Исторические периоды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Событие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Месяц')),
                ('day', models.IntegerField(blank=True, null=True, verbose_name='День')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/events/')),
                ('is_featured', models.BooleanField(default=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='history.historicalperiod')),
            ],
            options={
                'verbose_name': 'Историческое событие',
                'verbose_name_plural': 'Исторические события',
                'ordering': ['year', 'month', 'day'],
            },
        ),
    ]
